export const forfrontItems = [
    {
        name: "day",
        mainComponent: "./media/Sol.svg",
        small1: "./media/cloud.svg",
        small2: "./media/cloud.svg",
        small3: "./media/cloud.svg",
        small4: "./media/cloud.svg",
        small5: "./media/cloud.svg",
        small6: "./media/cloud.svg",
        small7: "./media/cloud.svg",
    },
        {
        name: "sunset",
        mainComponent: "./media/Sol.svg",
        small1: "./media/cloud.svg",
        small2: "./media/heart.svg",
        small3: "./media/heart.svg",
        small4: "./media/heart.svg",
        small5: "./media/heart.svg",
        small6: "./media/heart.svg",
        small7: "./media/heart.svg",
    },
        {
        name: "darkmode",
        mainComponent: "./media/moon.svg",
        small1: "./media/sstar-closed-eyes.svg",
        small2: "./media/star-closed-eyes.svg",
        small3: "./media/star-closed-eyes.svg",
        small4: "./media/star-closed-eyes.svg",
        small5: "./media/star-closed-eyes.svg",
        small6: "./media/star-closed-eyes.svg",
        small7: "./media/star-closed-eyes.svg",
    },
]