export const forfrontItems = [
    {
        name: "day",
        mainComponent: "./media/forgroundMode/Sol.svg",
        small1: "./media/forgroundMode/Moln-big.svg",
        small2: "./media/forgroundMode/Moln-small.svg",
        small3: "./media/forgroundMode/Moln-medium.svg",
        small4: "./media/forgroundMode/Moln-big.svg",
        small5: "./media/forgroundMode/Moln-medium.svg",
        small6: "./media/forgroundMode/Moln-small.svg",
        small7: "./media/forgroundMode/Moln-small.svg"
    },
        {
        name: "sunset",
        mainComponent: "./media/forgroundMode/Sol.svg",
        small1: "./media/forgroundMode/Hjärtan-medium-turned-l.svg",
        small2: "./media/forgroundMode/Hjärtan-medium-turned.svg",
        small3: "./media/forgroundMode/Hjärtan-small-turned.svg",
        small4: "./media/forgroundMode/Hjärtan-big-turned.svg",
        small5: "./media/forgroundMode/Hjärtan-small.svg",
        small6: "./media/forgroundMode/Hjärtan-small-turned.svg",
        small7: "./media/forgroundMode/Hjärtan-medium-turned.svg",
    },
        {
        name: "darkmode",
        mainComponent: "./media/forgroundMode/Måne.svg",
        small1: "./media/forgroundMode/Star-closedeyes-small.svg",
        small2: "./media/forgroundMode/Star-openeyes-big.svg",
        small3: "./media/forgroundMode/Star-closedeyes-small-turned.svg",
        small4: "./media/forgroundMode/Star-closedeyes-small.svg",
        small5: "./media/forgroundMode/Star-closedeyes-small.svg",
        small6: "./media/forgroundMode/Star-closedeyes-small-turned.svg",
        small7: "./media/forgroundMode/Star-closedeyes-small.svg",
    },
]