export const themes = [
    {
        name: "Babblarna",
        img: "./media/group-characters/babblarna-group.svg",
        characters: [
            {
                name: "Bibbi",
                theme: "Babblarna",
                imgTotal: "./media/babblarna/Bibbi.svg",
                imgPuzzle: "/media/babblarna/Bibbi-puzzle/Bibbi-full.svg",
                pussel1: "./media/babblarna/Bibbi-puzzle/bibbi-1.svg", 
                pussel2: "./media/babblarna/Bibbi-puzzle/bibbi-2.svg", 
                pussel3: "./media/babblarna/Bibbi-puzzle/bibbi-3.svg", 
                pussel4: "./media/babblarna/Bibbi-puzzle/bibbi-4.svg", 
                outline: "./media/babblarna/Bibbi-puzzle/Bibbi-outline.svg",
            },
            {
                name: "Bobbo",
                theme: "Babblarna",
                imgTotal: "../media/babblarna/Bobbo.svg",
                imgPuzzle: "/media/babblarna/Bobbo-puzzle/Bobbo-full.svg",
                pussel1: "./media/babblarna/Bobbo-puzzle/bobbo-1.svg", 
                pussel2: "./media/babblarna/Bobbo-puzzle/bobbo-2.svg", 
                pussel3: "./media/babblarna/Bobbo-puzzle/bobbo-3.svg", 
                pussel4: "./media/babblarna/Bobbo-puzzle/bobbo-4.svg", 
                outline: "./media/babblarna/Bobbo-puzzle/Bobbo-outline.svg",
            },
            {
                name: "Babba",
                theme: "Babblarna",
                imgTotal: "../media/babblarna/Babba.svg",
                imgPuzzle: "/media/babblarna/Babba-puzzle/Babba-puzzle.svg",
                pussel1: "./media/babblarna/Babba-puzzle/babba-1.svg", 
                pussel2: "./media/babblarna/Babba-puzzle/babba-2.svg", 
                pussel3: "./media/babblarna/Babba-puzzle/babba-3.svg", 
                pussel4: "./media/babblarna/Babba-puzzle/babba-4.svg", 
                outline: "./media/babblarna/Babba-puzzle/Babba-outline.svg" ,
            },
            {
                name: "Dadda",
                theme: "Babblarna",
                imgTotal: "/media/babblarna/Dadda.svg",
                imgPuzzle: "/media/babblarna/Dadda-puzzle/Dadda-full.svg",
                pussel1: "./media/babblarna/Dadda-puzzle/dadda-1.svg", 
                pussel2: "./media/babblarna/Dadda-puzzle/dadda-2.svg", 
                pussel3: "./media/babblarna/Dadda-puzzle/dadda-3.svg", 
                pussel4: "./media/babblarna/Dadda-puzzle/dadda-4.svg", 
                outline: "./media/babblarna/Dadda-puzzle/Dadda-outline.svg",
            },
            {
                name: "Doddo",
                theme: "Babblarna",
                imgTotal: "../media/babblarna/Doddo.svg",
                imgPuzzle: "/media/babblarna/Doddo-puzzle/Doddo-full.svg",
                pussel1: "./media/babblarna/Doddo-puzzle/Doddo-1.svg", 
                pussel2: "./media/babblarna/Doddo-puzzle/Doddo-2.svg", 
                pussel3: "./media/babblarna/Doddo-puzzle/Doddo-3.svg", 
                pussel4: "./media/babblarna/Doddo-puzzle/Doddo-4.svg", 
                outline: "./media/babblarna/Doddo-puzzle/Doddo-outline.svg",
            }

        ]
    },
        {
        name: "Paw patrol",
        img: "./media/group-characters/PawPatrol-characters.svg",
        characters: [
            {
                name: "Pawpantrol1",
                theme: "pawpatrol",
                imgTotal: "./media/pawpatrol/pawpatrol1-puzzle/pawPatrol1.svg",
                imgPuzzle: "./media/pawpatrol/pawpatrol1-puzzle/pawpatrol1-full.svg",
                pussel1: "./media/pawpatrol/pawpatrol1-puzzle/pawpatrol1-1.svg", 
                pussel2: "./media/pawpatrol/pawpatrol1-puzzle/pawpatrol1-2.svg", 
                pussel3: "./media/pawpatrol/pawpatrol1-puzzle/pawpatrol1-3.svg", 
                pussel4: "./media/pawpatrol/pawpatrol1-puzzle/pawpatrol1-4.svg", 
                pussel5: "./media/pawpatrol/pawpatrol1-puzzle/pawpatrol1-5.svg", 
                pussel6: "./media/pawpatrol/pawpatrol1-puzzle/pawpatrol1-6.svg", 
                pussel7: "./media/pawpatrol/pawpatrol1-puzzle/pawpatrol1-7.svg", 
                pussel8: "./media/pawpatrol/pawpatrol1-puzzle/pawpatrol1-8.svg", 
                pussel9: "./media/pawpatrol/pawpatrol1-puzzle/pawpatrol1-9.svg", 
                outline: "./media/pawpatrol/pawpatrol1-puzzle/pawpatrol1-outline.svg", 
            },
            {
                name: "Pawpantrol2",
                theme: "pawpatrol",
                imgTotal: "./media/pawpatrol/pawpatrol2-puzzle/pawPatrol2.svg",
                imgPuzzle: "./media/pawpatrol/pawpatrol2-puzzle/pawpatrol2-full.svg",
                pussel1: "./media/pawpatrol/pawpatrol2-puzzle/pawpatrol2-1.svg", 
                pussel2: "./media/pawpatrol/pawpatrol2-puzzle/pawpatrol2-2.svg", 
                pussel3: "./media/pawpatrol/pawpatrol2-puzzle/pawpatrol2-3.svg", 
                pussel4: "./media/pawpatrol/pawpatrol2-puzzle/pawpatrol2-4.svg", 
                pussel5: "./media/pawpatrol/pawpatrol2-puzzle/pawpatrol2-5.svg", 
                pussel6: "./media/pawpatrol/pawpatrol2-puzzle/pawpatrol2-6.svg", 
                pussel7: "./media/pawpatrol/pawpatrol2-puzzle/pawpatrol2-7.svg", 
                pussel8: "./media/pawpatrol/pawpatrol2-puzzle/pawpatrol2-8.svg", 
                pussel9: "./media/pawpatrol/pawpatrol2-puzzle/pawpatrol2-9.svg", 
                outline: "./media/pawpatrol/pawpatrol2-puzzle/pawpatrol2-outline.svg",
            },
            {
                name: "Pawpantrol3",
                theme: "pawpatrol",
                imgTotal: "./media/pawpatrol/pawpatrol3-puzzle/pawpatrol3.svg",
                imgPuzzle: "./media/pawpatrol/pawpatrol3-puzzle/pawpatrol3-full.svg",
                outline: "./media/pawpatrol/pawpatrol3-puzzle/pawpatrol3-outline.svg",
            },
            {
                name: "Pawpantrol4",
                theme: "pawpatrol",
                imgTotal: "./media/pawpatrol/pawpatrol4-puzzle/pawPatrol4.svg",
                imgPuzzle: "./media/pawpatrol/pawpatrol4-puzzle/pawpatrol4-full.svg",
                outline: "./media/pawpatrol/pawpatrol4-puzzle/pawpatrol4-outline.svg"
            },
        ]
    },
    {
        name: "Bamse",
        img: "./media/group-characters/bamse-characters.svg",
        characters: [
            {
                name: "Bamse",
                theme: "Bamse",
                imgPuzzle: "./media/bamse/bamse-puzzle/bamse-full.svg",
                imgTotal: "./media/bamse/bamse-puzzle/bamse.svg",
                pussel1: "./media/bamse/bamse-puzzle/Bamse-1.svg", 
                pussel2: "./media/bamse/bamse-puzzle/Bamse-2.svg", 
                pussel3: "./media/bamse/bamse-puzzle/Bamse-3.svg", 
                pussel4: "./media/bamse/bamse-puzzle/Bamse-4.svg", 
                pussel5: "./media/bamse/bamse-puzzle/Bamse-5.svg", 
                pussel6: "./media/bamse/bamse-puzzle/Bamse-6.svg", 
                pussel7: "./media/bamse/bamse-puzzle/Bamse-7.svg", 
                pussel8: "./media/bamse/bamse-puzzle/Bamse-8.svg", 
                pussel9: "./media/bamse/bamse-puzzle/Bamse-9.svg", 
                outline: "./media/bamse/bamse-puzzle/Bamse-outline.svg", 
            },
            {
                name: "Lille-Skutt",
                theme: "Bamse",
                imgTotal: "./media/bamse/lille-skutt-puzzle/lille-skutt.svg",
                imgPuzzle: "./media/bamse/lille-skutt-puzzle/lilleskutt-full.svg",
                pussel1: "./media/bamse/lille-skutt-puzzle/lilleskutt1.svg", 
                pussel2: "./media/bamse/lille-skutt-puzzle/lilleskutt2.svg", 
                pussel3: "./media/bamse/lille-skutt-puzzle/lilleskutt3.svg", 
                pussel4: "./media/bamse/lille-skutt-puzzle/lilleskutt4.svg", 
                pussel5: "./media/bamse/lille-skutt-puzzle/lilleskutt5.svg", 
                pussel6: "./media/bamse/lille-skutt-puzzle/lilleskutt6.svg", 
                pussel7: "./media/bamse/lille-skutt-puzzle/lilleskutt7.svg", 
                pussel8: "./media/bamse/lille-skutt-puzzle/lilleskutt8.svg", 
                pussel9: "./media/bamse/lille-skutt-puzzle/lilleskutt9.svg", 
                outline: "./media/bamse/lille-skutt-puzzle/lilleskutt-outline.svg", 
            },
            {
                name: "Skalman",
                theme: "Bamse",
                imgTotal: "./media/bamse/skalman-puzzle/skalman.svg",
                imgPuzzle: "./media/bamse/skalman-puzzle/skalman-full.svg",
                pussel1: "./media/bamse/skalman-puzzle/skalman1.svg", 
                pussel2: "./media/bamse/skalman-puzzle/skalman2.svg", 
                pussel3: "./media/bamse/skalman-puzzle/skalman3.svg", 
                pussel4: "./media/bamse/skalman-puzzle/skalman4.svg", 
                pussel5: "./media/bamse/skalman-puzzle/skalman5.svg", 
                pussel6: "./media/bamse/skalman-puzzle/skalman6.svg", 
                pussel7: "./media/bamse/skalman-puzzle/skalman7.svg", 
                pussel8: "./media/bamse/skalman-puzzle/skalman8.svg", 
                pussel9: "./media/bamse/skalman-puzzle/skalman9.svg", 
                outline: "./media/bamse/skalman-puzzle/skalman-outline.svg", 
            },
            {
                name: "Farmor",
                theme: "Bamse",
                imgTotal: "./media/bamse/farmor-puzzle/farmor.svg",
                imgPuzzle: "./media/bamse/farmor-puzzle/farmor-full.svg",
                pussel1: "./media/bamse/farmor-puzzle/farmor1.svg", 
                pussel2: "./media/bamse/farmor-puzzle/farmor2.svg", 
                pussel3: "./media/bamse/farmor-puzzle/farmor3.svg", 
                pussel4: "./media/bamse/farmor-puzzle/farmor4.svg", 
                pussel5: "./media/bamse/farmor-puzzle/farmor5.svg", 
                pussel6: "./media/bamse/farmor-puzzle/farmor6.svg", 
                pussel7: "./media/bamse/farmor-puzzle/farmor7.svg", 
                pussel8: "./media/bamse/farmor-puzzle/farmor8.svg", 
                pussel9: "./media/bamse/farmor-puzzle/farmor9.svg", 
                outline: "./media/bamse/farmor-puzzle/farmor-outline.svg", 
            }
        ]
    }
];